### ISSUE TITLE
Linting

### ISSUE THREAD

**Issue by cjshawMIT** [CLIxIndia-Dev/physics-video-player#3]
It would be nice if this code were linted for consistency...currently there are weird indenting issues (possibly spaces vs. tabs?):

Example:
```
    inputNode = document.getElementById('input'); 
	inputNode.addEventListener('change', playFile, false);
	initButtons();
```

**Comment by brandonhanks** [comment]
Now linted with ESLint. Thanks!

**Comment by cjshawMIT** [comment]
@brandonhanks nice! If you could include the `.eslintrc` file (or equivalent for however you linted) into the repo, that would help others understand the conventions used for this project.

**Comment by brandonhanks** [comment]
Added, thanks for the idea!
